config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: "registrations" }
  root 'static_pages#home'
  get '/search', to: 'quotes#search'
  namespace :api do
    namespace :v1 do
      root 'quotes#index'
      resources :quotes, only: [:index, :show, :random]
      get '/random', to: 'quotes#random'
      get '/search', to: 'quotes#search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quotes
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :quote, presence: true, uniqueness: true
  validates :person, presence: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_action :set_default_format
  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/api/v1/quotes_controller.rb
class Api::V1::QuotesController < Api::V1::BaseController
  def index
    @quotes = Quote.paginate(page: params[:page], per_page: 10)
    render json: @quotes
  end

  def show
    @quote = Quote.find(params[:id])
    render json: @quote
  end

  def random
    offset = rand(Quote.count)
    @quote = Quote.offset(offset).first
    render json: @quote
  end

  def search
    @quotes = Quote.where("person = ?", params[:q]).paginate(page: params[:page])
    render json: @quotes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  protect_from_forgery
  before_action :authenticate_admin!, only: [:create, :edit, :update, :destroy]
  before_action :set_quote, only: [:edit, :update, :destroy]

  def index
    @quotes = Quote.order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      flash[:success] = "Quote created successfully"
      redirect_to quotes_path
    else
      render "quotes/new"
    end
  end

  def edit

  end

  def update
    if @quote.update(quote_params)
      flash[:success] = "Quote updated successfully"
      redirect_to quotes_path
    else
      render action: 'edit'
    end
  end

  def destroy
    if @quote.destroy
      flash[:success] = "Quote deleted"
    else
      flash[:danger] = "Couldn't delete quote"
    end
    redirect_to quotes_path
  end

  def search
    @quotes = Quote.where("person = ?", params[:q]).paginate(page: params[:page])
  end

  private
  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:quote, :person)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if Admin.count == 1
      if admin_signed_in?
        redirect_to root_path
      else
        redirect_to new_admin_session_path
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar nav-expand navbar-dark bg-dark">
  <h1 class="nav-brand"><%= link_to 'Quotes-API', root_path, class: 'nav-link text-white' %></h1>
  <%= link_to 'Quotes', quotes_path, class: 'nav-link nav-item text-white' %>
  <form action="/search">
    <input class="form-control" type="text" name="q" placeholder="Search...">
  </form>
  <% if admin_signed_in? %>
    <%= link_to 'Logout', destroy_admin_session_path, :method => :delete, class: 'nav-link nav-item text-white'  %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<div class="container">
  <%= form_for @quote do |f| %>
    <%= f.text_area :quote, autocomplete: 'off', placeholder: "Write the quote here....", class: 'form-control mb-2' %>
    <%= f.text_field :person, placeholder: 'Person' ,class: 'form-control mb-3' %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/quotes/_quotes.html.erb
<% @quotes.each do |quote| %>
  <div class="card mb-4">
    <div class="card-body">
      <p class="card-text">
        <i>"<%= quote.quote %>"</i>
      <h6 class="float-right"><%= quote.person %></h6>
      <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_quote_path(quote) %> |
        <%= link_to 'Delete', quote_path(quote), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </p>
    </div>
  </div>
<% end %>
<div class="digg_pagination">
  <%= will_paginate %>
</div>

app/views/quotes/edit.html.erb
<h1>Edit quote</h1>

<%= render 'quotes/form' %>

app/views/quotes/index.html.erb
<div class="container">
  <br>
  <% if admin_signed_in? %>
    <div class="text-center">
      <%=  link_to 'Create Quote', new_quote_path, class: 'btn btn-primary mb-3' %>
    </div>
  <% end %>
  <%= render 'quotes/quotes' %>
</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'quotes/form' %>

app/views/quotes/search.html.erb
<div class="container">
  <br>
    <%= render 'quotes/quotes' %>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <h3>What is this API for? </h3>
  <p>This is a simple API that returns quotes from famous people.
    The data is returned in JSON format. It's free and doesn't need a key.  </p>
  <h3>How to use it?</h3>
  <p>
    <ul>
      <li>The API's endpoint is: <code>/api/v1/</code> or <code>/api/v1/quotes</code> Returns the first 10 quotes in the database.</li>
      <li>To navigate between pages: <code>/api/v1/quotes?page=:number</code></li>
      <li><code>/api/v1/quotes/:id</code> returns the quote that belongs to the id given</li>
      <li>The search function's endpoint is <code>api/v1/search/?q=:person</code>.
        The query only accepts the person name </li>
      <li>The random function returns a random quote and its endpoint is: <code>api/v1/random/</code> </li>
    </ul>

    <h5>Returned fields</h5>
    <ul>
      <li><code>id</code>: The id of the quote</li>
      <li><code>person</code>: Person who belongs the quote</li>
      <li><code>quote</code>: The quote itself</li>
      <li><code>created_at</code>: When was created in the database</li>
      <li><code>updated_at</code>: When was updated in the database</li>
    </ul>
  </p>
  <h3>How to deploy it?</h3>
  <p>
    To test locally, install dependencies using <code>bundle install</code>.
  </p>
  <p>
    After that run the command <code>rails db:migrate</code> to create and initialize the database,
    populate the database with <code>rails db:seed</code> and then run the API using <code>rails s</code> or
    <code>rails server</code>.
  </p>
  <p>
    The API will be running on <code>localhost:3000</code>.
  </p>
  <small>
    <p>
      Ruby version 2.6.4
      Ruby on Rails 6
    </p>
  </small>
</div>